spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://cafe.cymo4x1xzhys.ap-northeast-2.rds.amazonaws.com:3306/cafein
    username: admin
    password: cafe1234
    driver-class-name: com.mysql.cj.jdbc.Driver